name: evently_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  flutter_svg:
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  flutter_bounceable: ^1.2.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2

dev_dependencies:
  build_runner:
  flutter_gen_runner:

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/core/gen/
  integrations:
    image: true
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/files/
    - assets/fonts/
    - assets/icons/
    - assets/animations/
    - assets/3d_models/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
